### Vault Config ###
spring:
  config:
    import: optional:vault://
  cloud:
    vault:
      enabled: true
      uri: ${VAULT_URL}
      authentication: token
      token: ${VAULT_TOKEN}
      kv:
        enabled: true
  application:
    name: bileton-trip